config:
    design_space:
        testnum: [10]
        RA: [5e-12, 10e-12, 15e-12, 
            20e-12]
        TMR: [100, 150, 200, 
             250, 300, 350, 
             400]
        gain1: [5, 6, 7,
               8, 9, 10,
               11, 12, 13,
               14, 15, 16,
               17, 18, 19,
               20]
        gain2: [5, 6, 7,
               8, 9, 10,
               11, 12, 13,
               14, 15, 16,
               17, 18, 19,
               20]     
       
